(* generated by dune *)

(** @canonical Mirage_crypto_rng_unix.Getentropy *)
module Getentropy = Mirage_crypto_rng_unix__Getentropy

(** @canonical Mirage_crypto_rng_unix.Urandom *)
module Urandom = Mirage_crypto_rng_unix__Urandom
