(* generated by dune *)

(** @canonical Ppxlib_jane.Ast_builder *)
module Ast_builder = Ppxlib_jane__Ast_builder

(** @canonical Ppxlib_jane.Ast_builder_intf *)
module Ast_builder_intf = Ppxlib_jane__Ast_builder_intf

(** @canonical Ppxlib_jane.Jane_asttypes *)
module Jane_asttypes = Ppxlib_jane__Jane_asttypes

(** @canonical Ppxlib_jane.Jane_syntax *)
module Jane_syntax = Ppxlib_jane__Jane_syntax

(** @canonical Ppxlib_jane.Jane_syntax_parsing *)
module Jane_syntax_parsing = Ppxlib_jane__Jane_syntax_parsing

(** @canonical Ppxlib_jane.Language_extension *)
module Language_extension = Ppxlib_jane__Language_extension

(** @canonical Ppxlib_jane.Language_extension_kernel *)
module Language_extension_kernel = Ppxlib_jane__Language_extension_kernel

(** @canonical Ppxlib_jane.Shadow_compiler_distribution *)
module Shadow_compiler_distribution = Ppxlib_jane__Shadow_compiler_distribution

module Ppxlib_jane__ = struct end
[@@deprecated "this module is shadowed"]
