.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "CMDLINER" 1 "" "Cmdliner v2.0.0" "Cmdliner Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
cmdliner \N'45' Helper tool for cmdliner based tools
.SH SYNOPSIS
.P
\fBcmdliner\fR [\fICOMMAND\fR] …
.SH DESCRIPTION
.P
\fBcmdliner\fR is a helper for tools using the cmdliner command line interface library\N'46' It helps with installing command line completion scripts and manpages\N'46' See the library documentation or invoke subcommands with \fB\N'45'\N'45'help\fR for more details\N'46'
.SH COMMANDS
.TP 4
\fBgeneric\N'45'completion\fR [\fIOPTION\fR]… \fISHELL\fR
Output generic completion scripts
.TP 4
\fBinstall\fR \fICOMMAND\fR …
Install support files for cmdliner tools
.TP 4
\fBtool\N'45'commands\fR [\fIOPTION\fR]… \fITOOLEXEC\fR
Output all subcommands of a cmdliner tool
.TP 4
\fBtool\N'45'completion\fR [\fIOPTION\fR]… \fISHELL\fR \fITOOLNAME\fR
Output tool completion scripts
.SH COMMON OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH EXIT STATUS
.P
\fBcmdliner\fR exits with:
.TP 4
0
on success\N'46'
.TP 4
123
on indiscriminate errors reported on standard error\N'46'
.TP 4
124
on command line parsing errors\N'46'
.TP 4
125
on unexpected internal errors (bugs)\N'46'