.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "CMDLINER-TOOL-COMPLETION" 1 "" "Cmdliner v2.0.0" "Cmdliner Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
cmdliner\N'45'tool\N'45'completion \N'45' Output tool completion scripts
.SH SYNOPSIS
.P
\fBcmdliner tool\N'45'completion\fR [\fIOPTION\fR]… \fISHELL\fR \fITOOLNAME\fR
.SH DESCRIPTION
.P
\fBcmdliner tool\N'45'completion\fR outputs the tool specific completion script of a given shell\N'46' Example:
.P
.nf
\fBcmdliner tool\N'45'completion\fR \fBzsh mytool\fR
.fi
.P
Note that tool specific completion script need the corresponding generic completion script output by \fBgeneric\N'45'completion\fR to be loaded in the shell\N'46' To install these scripts see command \fBinstall tool\N'45'completion\fR\N'46'
.SH ARGUMENTS
.TP 4
\fISHELL\fR (required)
\fISHELL\fR the shell to support, must be either \fBbash\fR or \fBzsh\fR\N'46'
.TP 4
\fITOOLNAME\fR (required)
\fITOOLNAME\fR is the name of the tool to complete\N'46'
.SH COMMON OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH EXIT STATUS
.P
\fBcmdliner tool\N'45'completion\fR exits with:
.TP 4
0
on success\N'46'
.TP 4
123
on indiscriminate errors reported on standard error\N'46'
.TP 4
124
on command line parsing errors\N'46'
.TP 4
125
on unexpected internal errors (bugs)\N'46'
.SH SEE ALSO
.P
cmdliner(1)