opam-version: "2.0"
lib: [
  "_build/install/default/lib/ohex/META"
  "_build/install/default/lib/ohex/dune-package"
  "_build/install/default/lib/ohex/ohex.a"
  "_build/install/default/lib/ohex/ohex.cma"
  "_build/install/default/lib/ohex/ohex.cmi"
  "_build/install/default/lib/ohex/ohex.cmt"
  "_build/install/default/lib/ohex/ohex.cmti"
  "_build/install/default/lib/ohex/ohex.cmx"
  "_build/install/default/lib/ohex/ohex.cmxa"
  "_build/install/default/lib/ohex/ohex.ml"
  "_build/install/default/lib/ohex/ohex.mli"
  "_build/install/default/lib/ohex/opam"
]
doc: [
  "_build/install/default/doc/ohex/CHANGES.md"
  "_build/install/default/doc/ohex/LICENSE.md"
  "_build/install/default/doc/ohex/README.md"
]
libexec: "_build/install/default/lib/ohex/ohex.cmxs"
