(* generated by dune *)

(** @canonical Cohttp_lwt_unix.Debug *)
module Debug = Cohttp_lwt_unix__Debug

(** @canonical Cohttp_lwt_unix.Input_channel *)
module Input_channel = Cohttp_lwt_unix__Input_channel

(** @canonical Cohttp_lwt_unix.Io *)
module Io = Cohttp_lwt_unix__Io

(** @canonical Cohttp_lwt_unix.Net *)
module Net = Cohttp_lwt_unix__Net

(** @canonical Cohttp_lwt_unix.Server *)
module Server = Cohttp_lwt_unix__Server

module Cohttp_lwt_unix__ = struct end
[@@deprecated "this module is shadowed"]
