(* generated by dune *)

(** @canonical Cohttp_lwt.Body *)
module Body = Cohttp_lwt__Body

(** @canonical Cohttp_lwt.Bytebuffer *)
module Bytebuffer = Cohttp_lwt__Bytebuffer

(** @canonical Cohttp_lwt.Client *)
module Client = Cohttp_lwt__Client

(** @canonical Cohttp_lwt.Connection *)
module Connection = Cohttp_lwt__Connection

(** @canonical Cohttp_lwt.Connection_cache *)
module Connection_cache = Cohttp_lwt__Connection_cache

(** @canonical Cohttp_lwt.Make *)
module Make = Cohttp_lwt__Make

(** @canonical Cohttp_lwt.S *)
module S = Cohttp_lwt__S

(** @canonical Cohttp_lwt.Server *)
module Server = Cohttp_lwt__Server

(** @canonical Cohttp_lwt.String_io *)
module String_io = Cohttp_lwt__String_io

module Cohttp_lwt__ = struct end
[@@deprecated "this module is shadowed"]
